Iter13
lionslon/go-yapmetrics pull request #14
Opened 2023-12-11 21:26 UTC by lionslon

2023-12-12 12:11 UTC, maxlyaptsev requested changes

2023-12-12 12:11 UTC, maxlyaptsev commented on internal/api/api.go
> +
Обсудили на 1-1, тут было бы хорошо навести порядок:

1. определяем хранилище storage =  database/fileStorage
2. если нужно запускаем dump (storage.DumpEnabled)
3. если нужно делаем восстановление данных - storage.Resore


Сейчас два очень похожих вызова и получается дублирование - database.Restore + storing.Restore

2023-12-12 12:11 UTC, maxlyaptsev commented on internal/config/config.go
> +func (s *ServerConfig) New() *ServerConfig {
```suggestion
func  NewServer() *ServerConfig {
```
Обсудили что конструктор должен быть функцией а не методом

2023-12-12 12:11 UTC, maxlyaptsev commented on internal/database/database.go
> +		query += fmt.Sprintf("INSERT INTO counter_metrics (name, value) VALUES ('%s', %d); ", k, v)
обсудили что  лучше использовать сторонний пакет, например https://github.com/jmoiron/sqlx т.к. возможны инъекции

2023-12-12 19:16 UTC, lionslon commented on internal/config/config.go
> +func (s *ServerConfig) New() *ServerConfig {
Реализовал инициализацию клиента и сервера через отдельные функции

2023-12-12 22:00 UTC, lionslon commented on internal/database/database.go
> +		query += fmt.Sprintf("INSERT INTO counter_metrics (name, value) VALUES ('%s', %d); ", k, v)
Переделал запросы к базе данных через использование sqlx

2023-12-14 14:54 UTC, lionslon commented on internal/api/api.go
> +
Реализовано обращение к хранилищам через интерфейс. Проведён рефакторинг функций сохранения и восстановления из файла и базы данных. Улучшена структура проекта.

2023-12-14 21:38 UTC, maxlyaptsev commented on internal/storage/database.go
> +	tx.MustExec("TRUNCATE counter_metrics, gauge_metrics; ")
проблема Must в том что они вызывают панику, что не очень хорошо. Лучше использовать обычные методы

2023-12-15 15:54 UTC, lionslon commented on internal/storage/database.go
> +	tx.MustExec("TRUNCATE counter_metrics, gauge_metrics; ")
Да, я как раз и хотел впадать в панику если с бд проблемы, например она отвалилась, т.к. у нас в проекте не используется никаких брокеров сообений. Но,  если лучше не впадать в панику когда что-то не так с используемыми компонентами, то окей - переделаю

2023-12-18 13:12 UTC, maxlyaptsev commented on internal/storage/database.go
> +	dbc.DB, err = sqlx.Open("postgres", dsn)
нужно еще явно закрыть соединение при завершении приложения

2023-12-18 13:14 UTC, maxlyaptsev approved these changes

2023-12-28 04:44 UTC, merged