Iter15
lionslon/go-yapmetrics pull request #16
Opened 2024-07-11 21:13 UTC by lionslon

2024-07-16 22:55 UTC, avhitrov requested changes
Много вопросов к реализации агента, в комментариях к коду. Кроме того, у меня есть стойкое ощущение, что к этой итерации должен уже быть создан эндпоинт и функция отправки метрик сразу пачкой.

2024-07-16 22:55 UTC, avhitrov commented on cmd/agent/main.go
> +	valuesGauge["CPUutilization1"] = float64(cpm)
Неверно понято задание. Метрика должна формироваться как CPUUtilizationN, где N = 1..количество процессоров в системе. `cpu.Counts` как раз позволяет выставить верхнюю планку, а сохранять в метрику необходимо результат работы функции [Percent](https://github.com/shirou/gopsutil/blob/v4.24.6/cpu/cpu.go#L149) [¶](https://pkg.go.dev/github.com/shirou/gopsutil/v4@v4.24.6/cpu#Percent)

2024-07-16 22:55 UTC, avhitrov commented on cmd/agent/main.go
> +				getExtraMetrics()
Неверно понято задание. `getMetrics` и `getExtraMetrics` должны выполняться в разных горутинах. Для их синхронизации как раз понадобится WaitGroup. И сразу хочу предупредить, что в этом случае без блокировок мы попадем на DATA RACE.

2024-07-16 22:55 UTC, avhitrov commented on cmd/agent/main.go
> +func postJSON(c *retryablehttp.Client, url string, m models.Metrics, password string) {
```suggestion
func postJSON(c *retryablehttp.Client, url string, m models.Metrics, password string) error {
```

2024-07-16 22:55 UTC, avhitrov commented on cmd/agent/main.go
>  	defer resp.Body.Close()
Если сервер недоступен, то вот здесь мы падаем:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x140468202]

goroutine 1 [running]:
main.postJSON(0xc0000d6150, {0xc00009c020, 0x1d}, {{0x1405ca7bc, 0x8}, {0x1405c9b53, 0x5}, 0x0, 0xc000076068})
        C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:112 +0x502
main.postQueries(0xc000098780)
        C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:81 +0x307
main.main()
        C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:34 +0x252
```

2024-07-16 22:55 UTC, avhitrov commented on cmd/agent/main.go
> +	postJSON(client, url1, models.Metrics{ID: "testCounter", MType: "counter"}, cfg.SignPass)
Не очень понятно, что делает этот вызов и для чего вообще у сервера спрашивать несуществующую метрику.

2024-07-16 22:55 UTC, avhitrov commented on cmd/agent/main.go
>  	pollCount = 0
Следует сбрасывать только в том случае, если `postJSON(client, url, models.Metrics{ID: "PollCount", MType: "counter", Delta: &pc}, cfg.SignPass)` завершилась без ошибок.

2024-07-19 17:57 UTC, lionslon commented on cmd/agent/main.go
> +				getExtraMetrics()
Переделал

2024-07-19 17:57 UTC, lionslon commented on cmd/agent/main.go
>  	defer resp.Body.Close()
Переделал

2024-07-19 17:58 UTC, lionslon commented on cmd/agent/main.go
> +	postJSON(client, url1, models.Metrics{ID: "testCounter", MType: "counter"}, cfg.SignPass)
Использовал для тестов, убрал

2024-07-19 17:58 UTC, lionslon commented on cmd/agent/main.go
>  	pollCount = 0
Переделал

2024-08-07 12:07 UTC, lionslon commented
@avhitrov батчи уже были реализованы, просто не переделывал агента, сейчас добавил

2024-08-08 15:31 UTC, avhitrov requested changes
Комментарии учтены, осталось разрулить проблему с DATA RACE при обращении к хранилищу метрик в агенте.

2024-08-08 15:31 UTC, avhitrov commented on cmd/agent/main.go
>  	valuesGauge["FreeMemory"] = float64(vmm.Free)
Как и предупреждал, при разнесении процесса сбора в разные горутины, выплыла проблема гонок.
```
==================
WARNING: DATA RACE
Write at 0x00c000154600 by goroutine 11:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  main.getExtraMetrics()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:105 +0xd7
  main.main.func1.2()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:48 +0x71

Previous write at 0x00c000154600 by goroutine 10:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  main.getMetrics()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:73 +0xe4
  main.main.func1.1()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:44 +0x71

Goroutine 11 (running) created at:
  main.main.func1()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:46 +0xd6

Goroutine 10 (finished) created at:
  main.main.func1()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:42 +0x1c5
==================
```
https://t.me/bushigo/24

2024-08-08 15:31 UTC, avhitrov commented on cmd/agent/main.go
> +				postQueries(cfg)
При отправке тоже возникают гонки:
```
==================
WARNING: DATA RACE
Read at 0x00c000154600 by goroutine 20:
  runtime.mapiternext()
      C:/Apps/Go/src/runtime/map.go:862 +0x0
  runtime.mapiterinit()
      C:/Apps/Go/src/runtime/map.go:859 +0x23b
  main.main.func2.1()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:59 +0x33

Previous write at 0x00c000154600 by goroutine 21:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  main.getExtraMetrics()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:110 +0x204
  main.main.func1.2()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:48 +0x71

Goroutine 20 (running) created at:
  main.main.func2()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:58 +0xe4

Goroutine 21 (running) created at:
  main.main.func1()
      C:/work/src/github.com/lionslon/go-yapmetrics/cmd/agent/main.go:46 +0xd6
==================
```

2024-08-19 22:02 UTC, avhitrov approved these changes
Все отлично!

2024-08-21 14:14 UTC, merged