Increment 9 is done
lionslon/go-yapmetrics pull request #9
Opened 2023-10-03 10:22 UTC by lionslon

2023-11-28 23:16 UTC, maxlyaptsev requested changes

2023-11-28 23:16 UTC, maxlyaptsev commented on internal/config/config.go
> +	}
Это все заменяется одной строкой
err := env.Parse(&s);

2023-11-28 23:16 UTC, maxlyaptsev commented on internal/api/api.go
> +		}
в конструктор зашивать такую логику не очень ожидаемое поведение. Лучше вынести в отдельную функцию - start/run

2023-11-28 23:16 UTC, maxlyaptsev commented on cmd/agent/main.go
> +		fmt.Println(err)
добавили логгер, нужно его использовать и выводить с соответствующим уровнем

2023-11-28 23:16 UTC, maxlyaptsev commented on internal/api/api.go
> +	sugar := *logger.Sugar()
логер нам нужен будет во всем приложении, поэтому это один из редких случаев когда лучше использовать глобальную переменную

2023-11-28 23:16 UTC, maxlyaptsev commented on internal/storing/storing.go
> +func Store(s *storage.MemStorage, filePath string, storeInterval int) {
```suggestion
func IntervalDump(s *storage.MemStorage, filePath string, storeInterval int) {
```
хочется как-то видеть более явно что тут будет происходит постоянный дамп с интервалом
Можно назваить `DumpWorker` или назвавть пакет `workers`

2023-11-30 12:18 UTC, lionslon commented on internal/api/api.go
> +		}
Перенёс в функцию Start

2023-11-30 12:19 UTC, lionslon commented on internal/config/config.go
> +	}
Заменил парсинг переменных окружения среды для клиента и сервера на функцию библиотеки caarlos0/env

2023-11-30 12:20 UTC, lionslon commented on cmd/agent/main.go
> +		fmt.Println(err)
Переделал на вызов `zap.S().Error(err)`

2023-11-30 12:21 UTC, lionslon commented on internal/api/api.go
> +	sugar := *logger.Sugar()
Изменил вызов `zap.S()`

2023-11-30 12:22 UTC, lionslon commented on internal/storing/storing.go
> +func Store(s *storage.MemStorage, filePath string, storeInterval int) {
Изменил название функции на `IntervalDump`

2023-12-01 16:31 UTC, maxlyaptsev approved these changes

2023-12-10 16:57 UTC, lionslon commented
Спринт 2 завершен

2023-12-10 16:58 UTC, merged